# Generated by Django 4.0.4 on 2022-05-21 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0004_rename_user_author_user_alter_post_auto_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='Author',
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 21, 15, 26, 42, 574102), max_length=64),
        ),
    ]
