# Generated by Django 4.0.4 on 2022-05-21 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0005_rename_post_post_author_alter_post_auto_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 21, 15, 32, 59, 845249), max_length=64),
        ),
    ]
