# Generated by Django 4.0.4 on 2022-05-23 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0006_rename_author_post_author_alter_post_auto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 23, 11, 15, 34, 206632), max_length=64),
        ),
    ]
