# Generated by Django 4.0.4 on 2022-05-23 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0010_remove_comment_comment_user_comment_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 23, 14, 28, 38, 429343), max_length=64),
        ),
    ]
