# Generated by Django 4.0.4 on 2022-05-25 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0039_alter_post_auto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 25, 14, 6, 8, 407848), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 25, 14, 6, 8, 404848), max_length=64),
        ),
    ]
