# Generated by Django 4.0.4 on 2022-05-27 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0040_comment_auto_data_alter_post_auto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 27, 17, 18, 17, 791520), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 27, 17, 18, 17, 789521), max_length=64),
        ),
    ]
