# Generated by Django 4.0.4 on 2022-05-30 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0042_alter_comment_auto_data_alter_post_auto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 5, 30, 9, 38, 57, 7354), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 38, 57, 3353), max_length=64),
        ),
    ]
