# Generated by Django 4.0.4 on 2022-06-16 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0043_alter_comment_auto_data_alter_post_auto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 6, 16, 12, 6, 2, 281740), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 12, 6, 2, 279738), max_length=64),
        ),
    ]
