# Generated by Django 4.0.4 on 2022-07-15 21:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('News_Portal', '0048_alter_comment_auto_data_alter_post_auto_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='News_Portal.CategoryUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 7, 16, 0, 36, 7, 563321), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 0, 36, 7, 560324), max_length=64),
        ),
        migrations.AddField(
            model_name='categoryuser',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal.category'),
        ),
        migrations.AddField(
            model_name='categoryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='categoryuser',
            unique_together={('user', 'category')},
        ),
    ]
