# Generated by Django 4.0.4 on 2022-07-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0049_categoryuser_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 7, 20, 20, 47, 16, 796012), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 20, 47, 16, 794011), max_length=64),
        ),
    ]
