# Generated by Django 4.0.4 on 2022-08-02 17:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('News_Portal', '0051_alter_category_subscribers_alter_comment_auto_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='News_Portal.CategoryUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='auto_data',
            field=models.CharField(default=datetime.datetime(2022, 8, 2, 20, 23, 30, 575286), max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='auto_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 20, 23, 30, 573286), max_length=64),
        ),
    ]
